addons:
  economy:
    enabled: false
  calculator:
    enabled: false
  nbt:
    enabled: false # Experimental feature, enable at your own risk
  phones:
    enabled: false # Experimental feature, enable at your own risk
  listeners:
    enabled: true
  discord:
    enabled: false
    token: ""
    webhook_url: ""